### ISSUE TITLE
USB permission

### ISSUE THREAD

**Issue by sobrinho** [freshollie/UsbGps4Droid#14]
Hi there,

Is [this](https://stackoverflow.com/questions/13726583/bypass-android-usb-host-permission-confirmation-dialog/30563253#30563253) still the way to go?

My device isn't rooted and this USB popup is really annoying.

I know that `/dev/ttyACM0` is available to be read by any user/app, that helps somehow?

**Comment by freshollie** [comment]
Yeah, unfortunately it's an android issue.

**Comment by sobrinho** [comment]
I'm seeing some comments on StackOverflow that you may specify the USB device properties somehow and avoid that warning.

Have you seen this before?

**Comment by freshollie** [comment]
That is to do with usb accessory options. I attempted this route but it still didn't work. Why are you not able to root the device?

**Comment by sobrinho** [comment]
I'm using a Tinker Board S and the options are limited, some people were able to root but the documentation is still missing across the web.

The few tutorials you will find doesn't work at all 😞
