### ISSUE TITLE
APK of v2.2.0 lacks v1 signature/certificates

### ISSUE THREAD

**Issue by IzzySoft** [freshollie/UsbGps4Droid#18]
There are no certificates inside the APK, so I assume you forgot at least v1 signing. Could you please sign the APK and re-attach? Thanks!

**Comment by freshollie** [comment]
Oops. Didn't really know if the v1 signatures were required anymore so I didn't tick the box. Rebuilding now.

**Comment by IzzySoft** [comment]
Thanks! Explanation:

* v1 is still needed for Android 6 and below, which doesn't know about v2 as that was introduced with Android 7. So if you want to support users on devices with Android versions below 7, you ***must*** provide v1 signature.
* Starting with Android 7, v2 was introduced. Here v1 is optional and used as fallback.
* to be on the safe side, just tick both check boxes in Android Studio :wink:
