### ISSUE TITLE
Usage of SiRF options

### ISSUE THREAD

**Issue by abagos** [freshollie/UsbGps4Droid#29]
Hello, I have installed the apk in an Android Headunit for typical navigation usage (Sygic). Do I need to enable SiRF options? What are they useful for?
Thank you in advance,
Alex.

**Comment by freshollie** [comment]
I think the SiRF options are for disabling or enabling specific message to be sent from the GPS. If your GPS works I wouldn't worry about it :)

**Comment by abagos** [comment]
Thank you. It works; I only need to find out how to autostart the service.
